language: node_js

node_js:
  - v9

install:
  - npm install

script:
  - lerna bootstrap
  - lerna run build --scope @devinit-charts/core
  - lerna bootstrap
  - lerna run build --scope @devinit-charts/bar
  - lerna run build --scope @devinit-charts/line
  - lerna run build --scope @devinit-charts/pie
  - lerna run lint

cache:
  - node_modules
  - ~/.npm
  - yarn